import Foundation
import AVFoundation
import Combine
import FirebaseAuth

// MARK: - Meditation Script Structure
struct MeditationScript {
    let dayNumber: Int
    let title: String
    let durationMinutes: Int
    let segments: [(text: String, pause: TimeInterval)]
}

// MARK: - Guided Meditation Engine
class GuidedMeditationEngine: NSObject, ObservableObject, AVSpeechSynthesizerDelegate, AVAudioPlayerDelegate {
    static let shared = GuidedMeditationEngine()

    @Published var isSpeaking: Bool = false
    @Published var currentDayTitle: String? = nil

    // AVSpeechSynthesizer kept as fallback when no OpenAI key is available
    private let synthesizer = AVSpeechSynthesizer()
    private var pendingSegments: [(text: String, pause: TimeInterval)] = []
    private var currentSegmentIndex: Int = 0
    private let meditationScripts: [MeditationScript]

    // OpenAI TTS playback
    private var ttsPlayer: AVAudioPlayer?
    private var ttsTask: Task<Void, Never>?
    private var ttsCurrentTempURL: URL?
    private var currentPauseAfterSegment: TimeInterval = 0

    override init() {
        self.meditationScripts = GuidedMeditationEngine.buildAllScripts()
        super.init()
        synthesizer.delegate = self
        synthesizer.usesApplicationAudioSession = true
    }

    // MARK: - Public Methods

    @MainActor
    func play(day: MeditationDay) {
        stop()

        guard let script = meditationScripts.first(where: { $0.dayNumber == day.day }) else { return }

        currentDayTitle = day.title
        isSpeaking = true

        // 1. Start soft singing-bowl background at 18% volume
        AudioManager.shared.playMeditationBackground()

        // 2. Register track in Control Center / Lock Screen / Apple Watch
        AudioManager.shared.registerMeditationNowPlaying(
            title: day.title,
            durationMinutes: script.durationMinutes
        )

        // 3. Try pre-recorded bundled audio (generated by generate_meditations.sh)
        //    → best quality, zero tokens, works fully offline
        let fileName = String(format: "meditation_%02d", day.day)
        if let url = Bundle.main.url(forResource: fileName, withExtension: "m4a") {
            playBundledMeditation(url: url, script: script)
            return
        }

        // 4. Fallback: TTS segment-by-segment (OpenAI → AVSpeech)
        pendingSegments = script.segments
        currentSegmentIndex = 0
        speakNextSegment()
    }

    /// Plays a pre-recorded meditation .m4a from the app bundle.
    /// The singing-bowl background runs simultaneously via AudioManager.
    @MainActor
    private func playBundledMeditation(url: URL, script: MeditationScript) {
        do {
            let player = try AVAudioPlayer(contentsOf: url)
            player.delegate = self
            player.volume   = 1.0
            player.play()
            ttsPlayer = player          // reuse existing player slot
        } catch {
            // Bundled file failed — fall back to TTS
            print("Bundled meditation load error: \(error)")
            pendingSegments    = script.segments
            currentSegmentIndex = 0
            speakNextSegment()
        }
    }

    @MainActor
    func stop() {
        // Cancel any in-flight TTS request
        ttsTask?.cancel()
        ttsTask = nil

        // Stop TTS audio player and clean up temp file
        ttsPlayer?.stop()
        ttsPlayer = nil
        if let url = ttsCurrentTempURL {
            try? FileManager.default.removeItem(at: url)
            ttsCurrentTempURL = nil
        }

        synthesizer.stopSpeaking(at: .immediate)
        AudioManager.shared.stopMeditationBackground()
        isSpeaking = false
        currentDayTitle = nil
        pendingSegments = []
        currentSegmentIndex = 0
        AudioManager.shared.isPlaying = false
        AudioManager.shared.currentTrackTitle = nil
    }

    // MARK: - Private: Segment Dispatch

    @MainActor
    private func speakNextSegment() {
        guard currentSegmentIndex < pendingSegments.count else {
            // All segments finished — fade out background after 4 seconds
            DispatchQueue.main.asyncAfter(deadline: .now() + 4) {
                AudioManager.shared.stopMeditationBackground()
                AudioManager.shared.isPlaying = false
            }
            isSpeaking = false
            return
        }

        let (text, pause) = pendingSegments[currentSegmentIndex]
        currentSegmentIndex += 1
        currentPauseAfterSegment = pause

        // Try OpenAI TTS (natural human voice "nova")
        ttsTask = Task { [weak self] in
            guard let self = self else { return }
            do {
                // Garantir que há utilizador autenticado antes de chamar o TTS
                if FirebaseAuth.Auth.auth().currentUser == nil {
                    try await FirebaseAuth.Auth.auth().signInAnonymously()
                }
                let data = try await OpenAIService.shared.generateSpeech(text: text, voice: "nova", speed: 0.88)
                if Task.isCancelled { return }
                await MainActor.run { self.playTTSAudio(data: data) }
            } catch {
                // Fallback: AVSpeechSynthesizer (se não há rede ou token)
                if !Task.isCancelled {
                    await MainActor.run { self.fallbackSpeakText(text: text, pause: pause) }
                }
            }
        }
    }

    /// Writes OpenAI TTS MP3 data to a temp file and plays it with AVAudioPlayer.
    @MainActor
    private func playTTSAudio(data: Data) {
        // Clean up the previous segment's temp file
        if let prev = ttsCurrentTempURL { try? FileManager.default.removeItem(at: prev) }

        let tmpURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("alma_tts_\(UUID().uuidString).mp3")
        do {
            try data.write(to: tmpURL)
            ttsCurrentTempURL = tmpURL
            let player = try AVAudioPlayer(contentsOf: tmpURL)
            player.delegate = self
            player.volume = 1.0
            player.play()
            ttsPlayer = player
        } catch {
            // File write/init failed — fall back for this segment only
            print("TTS player init failed: \(error)")
        }
    }

    /// AVSpeechSynthesizer fallback — used when OpenAI TTS is unavailable.
    @MainActor
    private func fallbackSpeakText(text: String, pause: TimeInterval) {
        let utterance = AVSpeechUtterance(string: text)
        utterance.voice = getBestVoice()
        // Vary rate slightly per segment for a more human feel
        utterance.rate = Float.random(in: 0.38...0.43)
        utterance.pitchMultiplier = 0.92
        utterance.volume = 1.0
        utterance.postUtteranceDelay = pause
        synthesizer.speak(utterance)
    }

    private func getBestVoice() -> AVSpeechSynthesisVoice? {
        // Prefer enhanced (neural) voices on iOS 16+ — they sound genuinely natural
        let preferredIdentifiers = [
            "com.apple.ttsbundle.siri_luciana_pt-BR_compact",   // Siri Luciana PT-BR
            "com.apple.ttsbundle.Luciana-premium",
            "com.apple.ttsbundle.Luciana-compact",
            "com.apple.voice.premium.pt-BR.Luciana",
            "com.apple.voice.enhanced.pt-BR.Luciana",
        ]
        for id in preferredIdentifiers {
            if let voice = AVSpeechSynthesisVoice(identifier: id) { return voice }
        }
        // Fallback: any pt-BR voice available
        let allVoices = AVSpeechSynthesisVoice.speechVoices()
        if let enhanced = allVoices.first(where: { $0.language == "pt-BR" && $0.quality == .enhanced }) {
            return enhanced
        }
        if let any = allVoices.first(where: { $0.language == "pt-BR" }) { return any }
        if let ptPt = allVoices.first(where: { $0.language == "pt-PT" }) { return ptPt }
        return AVSpeechSynthesisVoice(language: "en-US")
    }

    // MARK: - AVSpeechSynthesizerDelegate (fallback path)
    @MainActor
    func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didFinish utterance: AVSpeechUtterance) {
        // Fallback path: synthesizer finished an utterance (postUtteranceDelay already applied)
        speakNextSegment()
    }

    // MARK: - AVAudioPlayerDelegate (TTS path)
    @MainActor
    func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully _: Bool) {
        // TTS audio finished — clean up temp file, wait for pause, then continue
        ttsPlayer = nil
        if let url = ttsCurrentTempURL {
            try? FileManager.default.removeItem(at: url)
            ttsCurrentTempURL = nil
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + currentPauseAfterSegment) { [weak self] in
            self?.speakNextSegment()
        }
    }

    // MARK: - Script Builder
    private static func buildAllScripts() -> [MeditationScript] {
        return [
            buildDay1(), buildDay2(), buildDay3(), buildDay4(), buildDay5(),
            buildDay6(), buildDay7(), buildDay8(), buildDay9(), buildDay10(),
            buildDay11(), buildDay12(), buildDay13(), buildDay14(), buildDay15(),
            buildDay16(), buildDay17(), buildDay18(), buildDay19(), buildDay20(),
            buildDay21(), buildDay22(), buildDay23(), buildDay24(), buildDay25(),
            buildDay26(), buildDay27(), buildDay28(), buildDay29(), buildDay30()
        ]
    }

    // MARK: - Day 1: Respira e Acalma
    private static func buildDay1() -> MeditationScript {
        return MeditationScript(
            dayNumber: 1,
            title: "Respira e Acalma",
            durationMinutes: 5,
            segments: [
                ("Encontra uma posição confortável. Deixa o teu corpo pousar completamente neste momento.", 4.0),
                ("Fecha os olhos suavemente. Não há nada a fazer agora. Nenhum lugar a ir. Apenas este momento.", 6.0),
                ("Observa o teu corpo inteiro. Sente o contacto com a cadeira, com o chão. Estás seguro. Estás protegido.", 5.0),
                ("Agora, traz a atenção para a tua respiração. Não a mudas. Apenas observas. A respiração natural da tua vida.", 6.0),
                ("Inspira lentamente pela nariz. Sente o ar fresco a entrar. Sente a tua barriga a expandir-se.", 5.0),
                ("Expira lentamente pela boca. Deixa ir. Deixa ir tudo o que não serves.", 7.0),
                ("Inspira novamente. Traz a calma e a paz para dentro de ti.", 5.0),
                ("Expira. Solta a tensão, a preocupação, a pressa.", 8.0),
                ("Continua assim. Respira. Com cada respiração, acalma-te mais. E mais. E mais.", 7.0),
                ("Grande silêncio agora. Apenas a respiração. Apenas este momento de paz profunda.", 25.0),
                ("Começa a sentir o corpo novamente. Os dedos dos pés. As mãos. O rosto.", 5.0),
                ("Num ritmo próprio, abre os olhos. Traz a calma contigo. Este presente é teu.", 4.0)
            ]
        )
    }

    // MARK: - Day 2: O Corpo como Lar
    private static func buildDay2() -> MeditationScript {
        return MeditationScript(
            dayNumber: 2,
            title: "O Corpo como Lar",
            durationMinutes: 6,
            segments: [
                ("Senta-te com dignidade. O teu corpo é um templo. Uma casa sagrada onde habita a vida.", 5.0),
                ("Fecha os olhos. Respira lentamente. Deixa cada respiração ser uma vinda a casa.", 6.0),
                ("Sente a base da coluna. Raízes profundas que te ancoram à terra.", 5.0),
                ("Sente o teu coração. Esse espaço central onde a vida pulsa. Onde o calor habita.", 6.0),
                ("Agora, faz um varrimento atento. Começa na tua coroa. A cabeça, face, boca, queixo.", 5.0),
                ("Desce pelo pescoço. Sente os ombros. Que carregam histórias, memórias, esperanças.", 6.0),
                ("O peito. Os pulmões. O coração. Este espaço aberto onde a vida respira dentro de ti.", 6.0),
                ("Desce pelo abdómen. O lugar da criatividade. O centro da tua força.", 5.0),
                ("As costas. Estas estruturas fortes que te sustêm e protegem.", 5.0),
                ("As pernas. Do quadril até aos pés. Raízes que te ligam ao chão.", 5.0),
                ("Sente o corpo inteiro agora. Uma unidade. Uma casa. Um templo de vida.", 8.0),
                ("Silêncio profundo. Habita este lar sagrado.", 20.0),
                ("Traz a consciência lentamente. Traz o gratidão pelo corpo que serves. Pelo lar que és.", 5.0),
                ("Abre os olhos com reverência.", 3.0)
            ]
        )
    }

    // MARK: - Day 3: Observar sem Julgar
    private static func buildDay3() -> MeditationScript {
        return MeditationScript(
            dayNumber: 3,
            title: "Observar sem Julgar",
            durationMinutes: 6,
            segments: [
                ("Instala-te confortavelmente. Respira profundamente. Este é um lugar de não-julgamento.", 5.0),
                ("Observa os pensamentos que surgem. Deixa-os vir como nuvens no céu.", 6.0),
                ("Não tens de os seguir. Não tens de os empurrar. Apenas observa.", 6.0),
                ("Um pensamento: \"Tenho de fazer isto.\" Nota-o. Uma nuvem cinzenta que passa.", 5.0),
                ("Outro: \"Não estou bem.\" Observa-o sem concordância. Apenas nota. Uma nuvem mais.", 6.0),
                ("Agora uma sensação: peso, tensão, dor. Olha para ela sem a atacar ou acariciar.", 6.0),
                ("A mente é como o céu. Os pensamentos e sensações são como o tempo. Vêm e vão.", 6.0),
                ("Tu és como o céu. Vasto. Espaçoso. Capaz de acolher tudo sem te seres afetado.", 7.0),
                ("Não é teu pensamento: é apenas um pensamento, passando pelo espaço da tua consciência.", 6.0),
                ("Não é a tua emoção: é apenas uma onda de energia, fluindo, transformando-se.", 6.0),
                ("Permanece como a testemha silenciosa. Observa tudo. Julgues nada.", 8.0),
                ("Silêncio vasto. Apenas observação. Apenas presença.", 22.0),
                ("Lentamente, traz a atenção de volta. Mantém a qualidade de observação atenta.", 5.0),
                ("Abre os olhos. Continua a observar o mundo sem julgar.", 4.0)
            ]
        )
    }

    // MARK: - Day 4: Ondas de Presença
    private static func buildDay4() -> MeditationScript {
        return MeditationScript(
            dayNumber: 4,
            title: "Ondas de Presença",
            durationMinutes: 7,
            segments: [
                ("Senta-te perto de tudo o que é natural. O som de água é aqui o teu guia.", 5.0),
                ("Imagina que estás à beira de um lago. Calmo. Silencioso. Profundo.", 6.0),
                ("Respira. Com cada respiração, uma onda de presença expande-se de dentro de ti.", 6.0),
                ("A primeira onda: a consciência do corpo. Sente-a a irradiar de ti em círculos crescentes.", 6.0),
                ("A segunda onda: a consciência do coração. Amor, bondade, aceitação que te envolvem.", 6.0),
                ("A terceira onda: a consciência vasta. Estás conectado a todas as coisas vivas.", 6.0),
                ("As ondas não têm limite. Não têm fronteira. Como água, movem-se e transformam-se.", 6.0),
                ("Tu és o centro destas ondas. E tu és também cada onda. Tudo é um.", 6.0),
                ("Cada respiração é uma onda nova de presença. Expandindo. Tocando. Transformando.", 6.0),
                ("Deixa que as ondas te purifiquem. Deixa que te renovem. Deixa que te acordem.", 7.0),
                ("Grande silêncio. As ondas continuam. Infinitas. Eternas. Sagradas.", 25.0),
                ("Lentamente, volta o ponto central. O corpo. Este momento. Este lugar.", 5.0),
                ("Abre os olhos. Continua a irradiar presença em ondas concêntricas.", 4.0)
            ]
        )
    }

    // MARK: - Day 5: Raízes
    private static func buildDay5() -> MeditationScript {
        return MeditationScript(
            dayNumber: 5,
            title: "Raízes",
            durationMinutes: 7,
            segments: [
                ("Imagina que és uma árvore. As tuas pernas são o tronco. Os teus pés são as raízes.", 5.0),
                ("Fecha os olhos. Respira. Sente-te a crescer para baixo. Profundamente.", 6.0),
                ("As tuas raízes descem pela pele. Através da pele. Para dentro da terra.", 6.0),
                ("Mais fundo. Sempre mais fundo. Procurando água. Procurando nutrição. Procurando a verdade.", 6.0),
                ("As raízes encontram a água fria, pura, que corre sob tudo. Bebem dela.", 6.0),
                ("Esta água antiga já nutriu inúmeras árvores. Inúmeras vidas. Agora nutre a ti.", 6.0),
                ("Sente a estabilidade das raízes. Não importa o vento. Não importa a tempestade.", 6.0),
                ("Tu estás ancorado. Tu estás seguro. Tu estás conectado à profundidade.", 6.0),
                ("Os galhos crescem para cima. A coroa alcança o céu. Mas o coração está nas raízes.", 7.0),
                ("Aqui está a força silenciosa. Aqui está a nutrição constante. Aqui está a verdade.", 7.0),
                ("Silêncio profundo como o solo fértil. Escuridão amorosa que sustenta tudo.", 20.0),
                ("Traz a consciência lentamente. Sente as tuas raízes. Ainda estão aqui.", 5.0),
                ("Abre os olhos. Estás ancorado. Sempre.", 3.0)
            ]
        )
    }

    // MARK: - Day 6: A Leveza Interior
    private static func buildDay6() -> MeditationScript {
        return MeditationScript(
            dayNumber: 6,
            title: "A Leveza Interior",
            durationMinutes: 8,
            segments: [
                ("Encontra o conforto. Respira lentamente. Hoje exploramos a leveza que habita em ti.", 5.0),
                ("O corpo é pesado. Mas dentro do corpo existe espaço. Existe leveza.", 6.0),
                ("Observa o espaço entre as moléculas do teu corpo. Espaço vasto. Espaço quieto.", 6.0),
                ("Observa o espaço dentro da tua mente. Entre um pensamento e o próximo. Claridade pura.", 6.0),
                ("Este espaço é leve como o ar. Como a luz. Impossível de carregar. Impossível de pesar.", 6.0),
                ("Deixa que este espaço se expanda. Que ocupe mais lugar no teu corpo.", 6.0),
                ("Os pensamentos pesados caem. As emoções densas dissolvem-se. Apenas leveza fica.", 6.0),
                ("Tu és tanto o peso quanto a leveza. Podes escolher onde colocas a atenção.", 6.0),
                ("Agora, escolhe a leveza. Deixa o corpo ficar pesado enquanto a consciência voa.", 6.0),
                ("Como uma gota de água que se torna vapor. Leve. Livre. Suspensa no ar.", 6.0),
                ("Esta leveza é sempre tua. Não podes perdê-la. Apenas esquecer-te dela.", 7.0),
                ("Grande silêncio leve. Flutua. Apenas flutua neste espaço infinito.", 25.0),
                ("Traz o corpo de volta. Mas mantém a leveza. Uma leveza que permanece contigo.", 5.0),
                ("Abre os olhos. Leve. Sempre leve.", 3.0)
            ]
        )
    }

    // MARK: - Day 7: Gratidão
    private static func buildDay7() -> MeditationScript {
        return MeditationScript(
            dayNumber: 7,
            title: "Gratidão",
            durationMinutes: 8,
            segments: [
                ("Senta-te com o coração aberto. Este dia é dedicado à gratidão pelo presente.", 5.0),
                ("Respira. Com cada respiração, traz à mente uma coisa pela qual estás grato.", 6.0),
                ("O corpo que respira. A respiração que sustenta a vida. O milagre simples do ar.", 6.0),
                ("Os olhos que veem. A luz que entra. O mundo que se revela em cores.", 6.0),
                ("Os ouvidos que escutam. Os sons que tocam a alma. A voz dos que amas.", 6.0),
                ("O coração que bate. Batida após batida. Constante. Fiel. Desde antes do nascimento.", 6.0),
                ("As mãos que tocam. Que trabalham. Que consolam. Que criam.", 5.0),
                ("Os pés que caminham. A terra que te sustenta. A jornada que é a vida.", 6.0),
                ("As dificuldades que te ensinaram. As dores que te tornaram sábio. A luta que te fortaleceu.", 6.0),
                ("Os que te amam. Os que te tocaram. Os que deixaram marcas no teu coração.", 6.0),
                ("O silêncio. O espaço. O tempo que tens neste momento para respirar e sentir.", 6.0),
                ("Silêncio cheio de gratidão. Cada respiração é um agradecimento ao universo.", 20.0),
                ("A gratidão transforma tudo. Faz do comum extraordinário. Do simples sagrado.", 5.0),
                ("Traz esta gratidão contigo. Permanece no teu coração. Sempre.", 4.0)
            ]
        )
    }

    // MARK: - Day 8: Espaço e Abertura
    private static func buildDay8() -> MeditationScript {
        return MeditationScript(
            dayNumber: 8,
            title: "Espaço e Abertura",
            durationMinutes: 9,
            segments: [
                ("Instala-te num lugar onde sintas espaço. Respira livremente. Hoje expandimos.", 5.0),
                ("Nota como o teu corpo ocupa espaço. Alguns centímetros. Alguns metros se considerarmos a aura.", 6.0),
                ("Mas o espaço dentro do corpo é muito maior. Pulmões cheios de ar. Coração com cavidades.", 6.0),
                ("A mente tem espaço infinito. Pode conter o universo. Pode conter a eternidade.", 6.0),
                ("Agora, deixa que as paredes do teu corpo se tornem permeáveis. O espaço exterior entra.", 6.0),
                ("Não és um recipiente fechado. És uma abertura. Uma porta. Um portal.", 6.0),
                ("Abre a coroa. O topo da tua cabeça é uma flor que desabrocha.", 6.0),
                ("Abre o coração. As costelas são pétalas que se abrem para o mundo.", 6.0),
                ("Abre o abdómen. O lugar da criatividade floresce e expande-se.", 6.0),
                ("Abre as mãos. As palmas ficam para cima, prontas para receber.", 6.0),
                ("Abre os pés. As solas tocam a terra e absorvem a sua energia.", 6.0),
                ("Tu és agora completamente aberto. Espaço dentro de espaço. Abertura dentro de abertura.", 7.0),
                ("Grande silêncio. Permanece aqui. Vasto. Permeável. Sem limites.", 28.0),
                ("Lentamente, recolhe a atenção. Mas mantém a abertura. Sempre aberto.", 5.0),
                ("Abre os olhos. Continua aberto ao milagre do agora.", 4.0)
            ]
        )
    }

    // MARK: - Day 9: A Luz que Habitas
    private static func buildDay9() -> MeditationScript {
        return MeditationScript(
            dayNumber: 9,
            title: "A Luz que Habitas",
            durationMinutes: 9,
            segments: [
                ("Senta-te como se estivesses iluminado por dentro. Porque estás. A vida é luz.", 5.0),
                ("Fecha os olhos. Vê a escuridão. É a tela em branco onde a luz pode dançar.", 6.0),
                ("Agora, imagina uma pequena luz no centro do teu coração. Quente. Dourada. Viva.", 6.0),
                ("Esta luz não vem de fora. É tua. É a luz da tua própria vida. A tua chama.", 6.0),
                ("Com cada respiração, a chama cresce. Mais brilhante. Mais quente. Mais clara.", 6.0),
                ("Observa a luz a expandir-se. Preenchendo o peito. Enchendo o coração.", 6.0),
                ("Sobe pela garganta. Ilumina os olhos. Brilha através da testa.", 6.0),
                ("Desce pelos braços. Enche as mãos com luz. As palmas brilham.", 6.0),
                ("Desce pelo tronco. Aquece o abdómen. Energiza o centro criativo.", 6.0),
                ("Desce pelas pernas. Enche os joelhos, os tornozelos, os pés de luz.", 6.0),
                ("Tu és agora um ser feito de luz. Pura luminescência. Radiância viva.", 7.0),
                ("Esta luz irradia para longe. Toca tudo o que encontra. Toca as pessoas que amas.", 7.0),
                ("Grande silêncio radiante. Apenas luz. Apenas brilho. Apenas verdade.", 25.0),
                ("A luz fica contigo. Sempre. Mesmo quando os olhos se fecham, ela brilha.", 5.0),
                ("Abre os olhos. Brilha. Sempre brilha.", 3.0)
            ]
        )
    }

    // MARK: - Day 10: Soltar
    private static func buildDay10() -> MeditationScript {
        return MeditationScript(
            dayNumber: 10,
            title: "Soltar",
            durationMinutes: 10,
            segments: [
                ("Encontra uma posição onde possas estar totalmente à vontade. Hoje aprendemos a soltar.", 5.0),
                ("Tudo o que tens, em algum momento, terás de soltar. Tudo o que amas, tudo o que temes.", 6.0),
                ("A vida inteira é um exercício de soltar. Nascemos soltando. Morremos soltando.", 6.0),
                ("Observa agora o que tens nesta vida. Não os bens. Mas as ideias. As crenças.", 6.0),
                ("A ideia de quem és. A crença de que não és suficiente. O medo de falhar.", 6.0),
                ("Imagina cada um destes no teu coração. Pesados. Densos. Presos.", 6.0),
                ("Com cada expiração, deixa um ir. Uma expiração, uma coisa. Sem drama. Sem resistência.", 6.0),
                ("Observa como eles flutuam para longe. Como fumo que se dissipa. Como nuvens que passam.", 6.0),
                ("O medo solta-se. A culpa solta-se. O remorso solta-se. A vergonha solta-se.", 6.0),
                ("A necessidade de estar certo solta-se. A raiva solta-se. O ressentimento solta-se.", 6.0),
                ("Aquilo que amas pode ser soltado com honra. Deixa ir àqueles que amaste. Sem os prender.", 7.0),
                ("Até à tua vida própria. Até à tua respiração. Permite que seja solta.", 7.0),
                ("Grande silêncio. O vazio sagrado que resulta da entrega completa.", 30.0),
                ("Lentamente, começa a reconstruir. Mas desta vez sem apego. Apenas presença.", 5.0),
                ("Abre os olhos. Está tudo bem deixar ir. Tudo bem deixar estar.", 4.0)
            ]
        )
    }

    // MARK: - Day 11: O Rio da Consciência
    private static func buildDay11() -> MeditationScript {
        return MeditationScript(
            dayNumber: 11,
            title: "O Rio da Consciência",
            durationMinutes: 10,
            segments: [
                ("Imagina-te sentado à beira de um rio largo. As águas fluem eternas. Claras. Puras.", 5.0),
                ("Este rio é a consciência. Flui através de tudo. Tudo emerge dele. Tudo regressa.", 6.0),
                ("Tu estás no rio. E o rio está em ti. Não há separação. Apenas fluxo.", 6.0),
                ("Os pensamentos são peixes que nadam nele. Os sentimentos são correntezas. As emoções são ondas.", 6.0),
                ("Observa o rio fluir. Não tentas controlá-lo. Não tentas detê-lo. Apenas observas.", 6.0),
                ("O rio traz coisas. Trazos de memória. Trazos de esperança. Trazos de medo.", 6.0),
                ("Deixa que passem. O rio leva tudo consigo. Nada fica retido para sempre.", 6.0),
                ("Agora, observa a origem do rio. Vem de montanhas nevadas. Vem de fontes sagradas.", 6.0),
                ("Vem de um lugar que é pureza. Claridade. Verdade absoluta.", 6.0),
                ("Tu também vens de lá. Sou um rio da consciência que flui desta fonte eterna.", 6.0),
                ("Observa a foz do rio. Mescla-se com o oceano. O individual torna-se universal.", 6.0),
                ("Tu também te mesclarás. Não és separado. Apenas estás neste momento a ter a forma do rio.", 7.0),
                ("Grande silêncio. O som do rio. O fluxo eterno da vida. Da consciência. Da verdade.", 28.0),
                ("Traz a atenção de volta. Mas permanece como o rio. Fluindo. Sempre fluindo.", 5.0),
                ("Abre os olhos. Deixa a vida fluir através de ti.", 4.0)
            ]
        )
    }

    // MARK: - Day 12: Amor-Bondade
    private static func buildDay12() -> MeditationScript {
        return MeditationScript(
            dayNumber: 12,
            title: "Amor-Bondade",
            durationMinutes: 11,
            segments: [
                ("Senta-te de coração aberto. Hoje cultivamos a bondade que habita em cada ser.", 5.0),
                ("Traz à mente um ser que naturalmente te causa amor. Pode ser uma criança. Um animal. Um mestre.", 6.0),
                ("Observa o amor que emerges por ele. Sinta-o no peito como um calor suave.", 6.0),
                ("Agora, imagina-te a enviar bondade para este ser. Cada respiração carrega mensagens de bem.", 6.0),
                ("Que estejas seguro. Que tenhas saúde. Que tenhas paz. Que tenhas alegria.", 6.0),
                ("Vê este ser recebendo as tuas bênçãos. Brilhando mais. Florindo.", 6.0),
                ("Agora, amplia o círculo. Traz alguém que amas. Um familiar. Um amigo. Um colega.", 6.0),
                ("Estende a mesma bondade. Que estejas seguro. Que tenhas saúde. Que tenhas paz.", 6.0),
                ("Agora alguém que é neutro. Que não conheces bem. Sem razão para gostar ou desgostar.", 6.0),
                ("Oferece bondade também a eles. São vidas. Sofrem como tu sofres. Desejam felicidade como tu.", 6.0),
                ("Agora, oferece bondade a alguém que te feriu. Que te decepcionar. Que te magoou.", 6.0),
                ("Isto é difícil. Mas o ódio te prejudica a ti mais que a eles. A bondade te liberta.", 6.0),
                ("Finalmente, oferece bondade a ti. A ti próprio. Ao teu corpo. À tua jornada.", 6.0),
                ("Que tu sejas seguro. Que tenhas saúde. Que tenhas paz. Que tenhas alegria.", 7.0),
                ("Grande silêncio. O coração transborda de bondade. Para todos os seres. Para toda a existência.", 25.0),
                ("Lentamente, volta. Mas mantém a bondade. Sempre no coração.", 5.0),
                ("Abre os olhos. Sê gentil. Contigo. Com todos.", 4.0)
            ]
        )
    }

    // MARK: - Day 13: Escuta Profunda
    private static func buildDay13() -> MeditationScript {
        return MeditationScript(
            dayNumber: 13,
            title: "Escuta Profunda",
            durationMinutes: 11,
            segments: [
                ("Fecha os olhos. Hoje aprendemos a escuta verdadeira. Não com os ouvidos. Com o ser.", 5.0),
                ("O mundo está sempre a falar. Os sons, os silêncios, os sussurros da vida.", 6.0),
                ("Mas a verdadeira escuta é diferente. É estar completamente presente. Sem julgamento.", 6.0),
                ("Escuta o teu coração. O que te diz agora? Qual é a sua verdade?", 6.0),
                ("Não respondas. Apenas escuta. Como se estivesses a ouvir uma voz antiga.", 6.0),
                ("Escuta o teu corpo. Que dores? Que desejos? Que sabedoria tem?", 6.0),
                ("Novamente, apenas escuta. Sem tentar corrigir. Sem julgar.", 6.0),
                ("Escuta o teu intuição. Aquela voz suave que vem de um lugar muito profundo.", 6.0),
                ("Escuta a vida ao teu redor. Os sons que oiço. Os silêncios entre eles.", 6.0),
                ("Escuta o universo. O que te fala através de sinais, coincidências, encontros.", 6.0),
                ("Escuta o presente. Este momento. O que tem para te ensinar.", 6.0),
                ("A escuta profunda é um ato de amor. De reverência. De abertura.", 6.0),
                ("Quando escutas verdadeiramente, sentes-te menos sozinho. Sentes-te conectado.", 6.0),
                ("Porque quando escutas, toda a vida está a falar contigo. Constantemente.", 6.0),
                ("Grande silêncio. O silêncio onde a verdade mora. Onde a vida sussurra seus segredos.", 28.0),
                ("Lentamente, traz a atenção. Mas permanece como aquele que escuta.", 5.0),
                ("Abre os olhos. Continua a escutar. Profundamente. Sempre.", 4.0)
            ]
        )
    }

    // MARK: - Day 14: O Campo do Possível
    private static func buildDay14() -> MeditationScript {
        return MeditationScript(
            dayNumber: 14,
            title: "O Campo do Possível",
            durationMinutes: 12,
            segments: [
                ("Imagina um campo infinito. Vazio de contenção. Cheio de potencial. Este é o teu verdadeiro lar.", 5.0),
                ("Antes de pensares, existe possibilidade. Antes de escolheres, existe liberdade.", 6.0),
                ("Aqui, neste campo, todas as realidades existem simultaneamente. Tudo é possível.", 6.0),
                ("Tu não és apenas aquele que ele és. És também aquele que podes ser.", 6.0),
                ("Sentes a liberdade disto? O libertador desta verdade?", 6.0),
                ("O passado não te prende aqui. As escolhas antigas são apenas pegadas na areia.", 6.0),
                ("O medo não tem poder aqui. A dúvida é apenas uma nuvem transitória.", 6.0),
                ("Aqui, podes reimaginar-te. Podes escolher uma identidade nova. Uma vida nova.", 6.0),
                ("Observa todas as possibilidades à tua volta. Inumeráveis. Iridescentes. Vivas.", 6.0),
                ("Qual delas chama o teu coração? Qual versão de ti deseja emergir?", 6.0),
                ("Não há urgência. Não há pressão. Apenas campo infinito onde tudo é permitido.", 6.0),
                ("Agora, imagina-te a escolher uma. Com toda a confiança. Com toda a coragem.", 6.0),
                ("Sente como mudaria a tua vida. Como floresceria. Como se expandiria.", 6.0),
                ("Tu estás aqui, agora, a criar a tua vida, a cada respiração, a cada pensamento.", 6.0),
                ("Grande silêncio. O infinito dos possíveis. Esperando por ti. Para ti.", 30.0),
                ("Traz a atenção de volta. Mas lembra-te: ainda estás no campo. A criação continua.", 5.0),
                ("Abre os olhos. Escolhe sabiamente. Cria conscientemente.", 4.0)
            ]
        )
    }

    // MARK: - Day 15: Integração do Caminho
    private static func buildDay15() -> MeditationScript {
        return MeditationScript(
            dayNumber: 15,
            title: "Integração do Caminho",
            durationMinutes: 12,
            segments: [
                ("Senta-te no meio da jornada. Olha para trás. Olha para a frente. Estás aqui, agora.", 5.0),
                ("Duas semanas de prática. Duas semanas de encontros com a tua própria vida.", 6.0),
                ("O que aprendeu? Não com a mente. Mas com o ser.", 6.0),
                ("Traz à memória um momento de claridade. Um instante onde tudo fez sentido.", 6.0),
                ("Sente a verdade desse momento. Ainda está vivo em ti. Ainda ressoa.", 6.0),
                ("Traz à memória um momento de dificuldade. Uma luta que ultrapassou.", 6.0),
                ("Observa como te tornou mais forte. Mais sábio. Mais compassivo.", 6.0),
                ("Agora, integra tudo isto. O aprendizado. A transformação. A jornada.", 6.0),
                ("Não és a pessoa que eras há duas semanas. Mas também não partiste com a antiga.", 6.0),
                ("Tu és uma síntese. Uma integração. Uma unidade de tudo o que vives.", 6.0),
                ("A jornada agora não é mais futura. É presente. Este momento. Este agora.", 6.0),
                ("Tudo o que praticou estava para chegar aqui. Ao repouso no coração.", 6.0),
                ("Ao conhecimento de que tu és inteiro. Já estás completo. Nada mais precisa de vir.", 6.0),
                ("Mas tudo que vir ainda será bem-vindo. Porque estás em paz com o que é.", 6.0),
                ("Grande silêncio. O silêncio de uma viagem que é também um repouso.", 30.0),
                ("Lentamente, traz a consciência. Carrega a integração contigo.", 5.0),
                ("Abre os olhos. Tu és a jornada. Tu és o destino. Tu és.", 4.0)
            ]
        )
    }

    // MARK: - Day 16: Expansão da Consciência
    private static func buildDay16() -> MeditationScript {
        return MeditationScript(
            dayNumber: 16,
            title: "Expansão da Consciência",
            durationMinutes: 13,
            segments: [
                ("Senta-te onde possas sentir o vasto céu acima. A terra abaixo. Hoje, expandimos além das formas.", 5.0),
                ("Tu és mais que o corpo. Mais que a mente. Mais que tudo o que podes nomear.", 6.0),
                ("O corpo é apenas a forma mais densa de quem és. Uma roupagem temporária.", 6.0),
                ("Dentro desta forma habita uma consciência infinita. Sem limites. Sem fronteiras.", 6.0),
                ("Expande a atenção para fora da pele. O espaço que te rodeia é também parte de ti.", 6.0),
                ("O ar que respiras é teu. As moléculas foram respiradas por inúmeros seres antes.", 6.0),
                ("Expande ainda mais. A casa é tua. A rua. A cidade. O país.", 6.0),
                ("A consciência não tem limite. Pode conter o planeta inteiro. Pode conter as estrelas.", 6.0),
                ("Observa como a tua separação é ilusão. Tu és um com tudo o que vês.", 6.0),
                ("A árvore que cresce longe. O oceano que flui. O céu que não tem fim.", 6.0),
                ("As pessoas que amas. Os desconhecidos que vês na rua. Todos são expressões do teu ser.", 6.0),
                ("E tu és expressão de todos eles. Somos uma consciência única que brinca a ser muitos.", 6.0),
                ("Agora expande para além do planeta. Para o espaço. Para o universo inteiro.", 6.0),
                ("Sentes a vastidão? O silêncio infinito? A paz que é tudo isto?", 6.0),
                ("Tu habitas aqui. Neste espaço infinito. Esta é a tua verdadeira casa.", 6.0),
                ("Grande silêncio. Você e o infinito são um. Sempre foram. Sempre serão.", 30.0),
                ("Traz a atenção de volta ao corpo. Mas mantém a vastidão. Sempre.", 5.0),
                ("Abre os olhos. Vasto. Infinito. Livre.", 4.0)
            ]
        )
    }

    // MARK: - Day 17: A Testemunha Silenciosa
    private static func buildDay17() -> MeditationScript {
        return MeditationScript(
            dayNumber: 17,
            title: "A Testemunha Silenciosa",
            durationMinutes: 13,
            segments: [
                ("Senta-te como um observador. Um testemunha. Alguém que vê tudo mas não é afetado por nada.", 5.0),
                ("Ao longo da vida, muito passou pelo teu corpo. Muitas pessoas. Muitas experiências.", 6.0),
                ("Mas a testemunha dentro permaneceu imune. Intocada. Serena.", 6.0),
                ("Esta testemunha não é a mente. A mente joga. Reage. Se identifica.", 6.0),
                ("A testemunha silenciosa observa a mente a brincar. E não quer saber.", 6.0),
                ("A testemunha não é o corpo. O corpo sofre. Envelhece. Morre.", 6.0),
                ("A testemunha observa o corpo a mudar. E permanece. Eterna. Indiferente.", 6.0),
                ("A testemunha não é as emoções. As emoções vão e vêm como tempestades.", 6.0),
                ("A testemunha observa as emoções. E fica quieta. Silenciosa. Segura.", 6.0),
                ("Quando aprendes a ser a testemunha, a vida muda. Não sofres mais pelos teus pensamentos.", 6.0),
                ("Não sofres pelas tuas emoções. Observas-as. Como filmes a passar num ecrã.", 6.0),
                ("Isto não é indiferença. É sabedoria. É liberdade.", 6.0),
                ("Como testemunha, podes agir com claridade. Porque não estás envolvido na confusão.", 6.0),
                ("Como testemunha, podes amar sem apego. Porque sabes que nada é teu. Nada é permanente.", 6.0),
                ("Agora, sê a testemunha. Silenciosa. Vasta. Eterna.", 6.0),
                ("Observa tudo o que passa. Sem julgar. Sem reter. Sem medo.", 6.0),
                ("Grande silêncio. A testemunha que observa o silêncio observando-se a si próprio.", 30.0),
                ("Permanece como testemunha. Traz isto contigo.", 5.0),
                ("Abre os olhos. Continua a observar. Sempre a testemunha. Sempre.", 4.0)
            ]
        )
    }

    // MARK: - Day 18: Compaixão Universal
    private static func buildDay18() -> MeditationScript {
        return MeditationScript(
            dayNumber: 18,
            title: "Compaixão Universal",
            durationMinutes: 14,
            segments: [
                ("Senta-te com o coração completamente aberto. Hoje reconhecemos o sofrimento de toda a vida.", 5.0),
                ("Todos sofrem. O executivo e o mendigo. O rei e a criança. Todos sofrem.", 6.0),
                ("Quando vês isto claramente, a compaixão emerge naturalmente. Sem esforço. Sem pretensão.", 6.0),
                ("Observa a vida ao teu redor. A grama que é cortada. A flor que murcha. O inseto que morre.", 6.0),
                ("Todos querem viver. Todos querem evitar o sofrimento. Todos querem ser felizes.", 6.0),
                ("Os animais selvagens que lutam pela sobrevivência. Os presos na prisão da ignorância.", 6.0),
                ("As crianças que nascem em pobreza. Os doentes sem remédio. Os idosos esquecidos.", 6.0),
                ("Aqueles que cometeram erros. Aqueles que prejudicaram outros. Eles também sofrem.", 6.0),
                ("Porque para ser capaz de fazer mal, tens de estar num estado de ignorância, medo, dor.", 6.0),
                ("A compaixão não significa aprovação. Significa entendimento. Significa abertura.", 6.0),
                ("Significa ver a humanidade mesmo naqueles que parecem inumanos.", 6.0),
                ("Agora, imagina a tua compaixão como uma luz que irradia. Tocando a vida inteira.", 6.0),
                ("Que todos os seres estejam livres do sofrimento. Que todos encontrem paz.", 6.0),
                ("Que todos os seres encontrem a causa da felicidade. Que ninguém fique sozinho.", 6.0),
                ("Que cada coração quebrado cicatrize. Que cada vida destruída seja renovada.", 6.0),
                ("Grande silêncio. A compaixão que é o tecido do universo. O amor que tudo une.", 32.0),
                ("Traz a compaixão contigo. Ela é a tua verdadeira natureza. Sempre.", 5.0),
                ("Abre os olhos. Sê compaixão. No mundo. Para tudo.", 4.0)
            ]
        )
    }

    // MARK: - Day 19: O Sonhador e o Sonho
    private static func buildDay19() -> MeditationScript {
        return MeditationScript(
            dayNumber: 19,
            title: "O Sonhador e o Sonho",
            durationMinutes: 14,
            segments: [
                ("Fecha os olhos. Agora pergunta: quem está a ter este sonho chamado vida?", 5.0),
                ("Tu podes estar numa cama agora. A dormir. E isto é um sonho.", 6.0),
                ("Neste sonho, parece real. Os sentimentos parecem verdadeiros. As pessoas parecem separadas.", 6.0),
                ("Mas quando acordas, percebes que era tudo uma projeção da tua mente.", 6.0),
                ("O que nos diz isto? Que a realidade acordada também pode ser uma projeção.", 6.0),
                ("Um sonho maior. O sonho do universo a sonhar em si próprio.", 6.0),
                ("Tu és simultaneamente o sonhador e o sonho. O que sonha e o que é sonhado.", 6.0),
                ("Os outros? Também projeções do teu sonho. Porque tudo o que vês é através da tua consciência.", 6.0),
                ("Isto não significa que não importam. Significa que tudo é mais profundo que parece.", 6.0),
                ("Tu não és apenas o personagem no sonho. És também a mente que sonha.", 6.0),
                ("E és também o vasto silêncio que contém todo o sonho.", 6.0),
                ("Se compreenderes isto, a vida muda. Deixas de ser tão sério. Mais leve.", 6.0),
                ("Porque reconheces a natureza lúdica da existência. É um jogo. É criação.", 6.0),
                ("Podes participar com alegria. Sem apego. Sabendo que é sonho, mas vivendo plenamente.", 6.0),
                ("Grande silêncio. O sonho que sonha a si próprio. A consciência que se brinca.", 30.0),
                ("Agora, começa a acordar. Lentamente. Mas leva a lembrança do sonho contigo.", 5.0),
                ("Abre os olhos. Ainda estás a sonhar. Mas sabes agora que és o sonhador.", 4.0)
            ]
        )
    }

    // MARK: - Day 20: Equanimidade
    private static func buildDay20() -> MeditationScript {
        return MeditationScript(
            dayNumber: 20,
            title: "Equanimidade",
            durationMinutes: 15,
            segments: [
                ("Senta-te de espinha direita. Hoje cultivamos a equanimidade. A paz inabalável.", 5.0),
                ("A equanimidade não é indiferença. É a capacidade de permanecer equilibrado em todas as circunstâncias.", 6.0),
                ("Como a montanha que permanece, enquanto as estações mudam ao seu redor.", 6.0),
                ("Observa as dualidades da vida. Ganho e perda. Sucesso e fracasso. Louvor e crítica.", 6.0),
                ("A maioria sofre porque está apegada ao ganho e aversão à perda.", 6.0),
                ("Mas a equanimidade diz: ambos vão passar. Ambos são impermanentes. Ambos são igualmente inúteis.", 6.0),
                ("Isto não significa inação. A equanimidade pode atuar. Mas sem se identificar com o resultado.", 6.0),
                ("Imagina um arqueiro que dispara a seta. Mas depois deixa ir. Não segue a seta com o olhar.", 6.0),
                ("Fez o seu melhor. Agora está em paz. A seta vai aonde tem de ir.", 6.0),
                ("Tu também podes ser assim. Faz o teu melhor. Depois deixa estar. Confia.", 6.0),
                ("A equanimidade é a base da verdadeira liberdade. Porque não és governado pelas circunstâncias.", 6.0),
                ("O medo não te move. A ganância não te move. O que quer que seja, permaneces firme.", 6.0),
                ("Como um rochedo no mar, enquanto as ondas batem à sua volta.", 6.0),
                ("Isto é a verdadeira força. Não a rigidez. Mas a flexibilidade com raízes profundas.", 6.0),
                ("Agora, cultiva isto em ti. Com cada respiração, mais equilibrado. Mais estável.", 6.0),
                ("Grande silêncio. O silêncio da montanha. Do oceano. Da eternidade.", 30.0),
                ("Traz a equanimidade contigo. Ela é o teu porto seguro. Sempre.", 5.0),
                ("Abre os olhos. Equilibrado. Sereno. Livre.", 4.0)
            ]
        )
    }

    // MARK: - Day 21: O Coração como Centro
    private static func buildDay21() -> MeditationScript {
        return MeditationScript(
            dayNumber: 21,
            title: "O Coração como Centro",
            durationMinutes: 15,
            segments: [
                ("Senta-te e traz toda a atenção para o centro do peito. Aqui. Neste espaço sagrado.", 5.0),
                ("O coração não é apenas um órgão. É o centro da tua vida. Da tua verdade. Da tua alma.", 6.0),
                ("Durante muito tempo, foste ensinado a viver da cabeça. A pensar. A julgar. A analisar.", 6.0),
                ("Mas a verdadeira inteligência vem do coração. A inteligência da vida. Da natureza.", 6.0),
                ("O coração sabe coisas que a mente nunca saberá. A mente questiona. O coração conhece.", 6.0),
                ("Imagina uma porta no centro do teu peito. Lentamente, abre-a.", 6.0),
                ("Dentro encontras uma câmara de luz. Warm. Segura. Viva.", 6.0),
                ("Aqui estão todos os teus amores. Todos os teus desejos verdadeiros. Toda a tua fé.", 6.0),
                ("Aqui também está o teu medo. A tua dor. A tua vulnerabilidade.", 6.0),
                ("Tudo isto é sagrado. Tudo isto é parte de quem és. Nada deve ser rejeitado.", 6.0),
                ("O coração que foi ferido é o coração que pode amar completamente.", 6.0),
                ("Porque aprendeu que a vida vale a pena. Apesar do sofrimento. Precisamente por causa dele.", 6.0),
                ("Agora, deixa que o coração vire a direcção da tua vida. Não a cabeça.", 6.0),
                ("O que quer o teu coração? O que te faz sentir inteiro? Para onde te pede para ires?", 6.0),
                ("Escuta bem. Porque esta é a voz que importa.", 6.0),
                ("Grande silêncio. O silêncio do coração que bateu desde o nascimento. Que batirá até à morte.", 30.0),
                ("Traz a atenção do coração contigo. Deixa que dirija tudo.", 5.0),
                ("Abre os olhos. Vive do coração. Sempre.", 4.0)
            ]
        )
    }

    // MARK: - Day 22: Vazio Luminoso
    private static func buildDay22() -> MeditationScript {
        return MeditationScript(
            dayNumber: 22,
            title: "Vazio Luminoso",
            durationMinutes: 16,
            segments: [
                ("Senta-te em completa quietude. Vamos explorar o vazio que é tudo.", 5.0),
                ("Tudo o que vês vem do vazio. Tudo o que és emerge do vazio. Repousa no vazio.", 6.0),
                ("Não é um vazio assustador. É luminoso. Cheio de potencial. Cheio de vida adormecida.", 6.0),
                ("Observa o espaço no teu corpo. Entre as células. Entre os átomos. Vazio. Imenso.", 6.0),
                ("Se remobasses tudo do material, ficarias com vazio. Mas que vazio! Cheio de energia.", 6.0),
                ("Observa o espaço na tua mente. Entre um pensamento e outro. Vazio puro.", 6.0),
                ("Este vazio é a tua natureza verdadeira. Não és a forma. Habitas o vazio.", 6.0),
                ("Agora, deixa todos os pensamentos caírem para o vazio. Deixa as sensações dissiparem-se.", 6.0),
                ("Deixa a identidade desaparecesse. Quem fica? Vazio. Mas um vazio consciente.", 6.0),
                ("Um vazio que observa. Um vazio que é. Um vazio que ama.", 6.0),
                ("Isto é meditação real. Não tornar-se vazio. Mas reconhecer-se já vazio.", 6.0),
                ("E neste vazio, toda a plenitude existe. Toda a possibilidade. Toda a liberdade.", 6.0),
                ("Sentes o medo desaparecer? Porque não há \"eu\" separado para ser ferido.", 6.0),
                ("Sentes a alegria? Porque o vazio é livre. Sem carga. Sem limite.", 6.0),
                ("Grande silêncio. O vazio luminoso que é a tua verdadeira casa. O lugar de repouso.", 35.0),
                ("Lentamente, volta. Mas mantém o vazio. Vive dentro dele. Sempre.", 5.0),
                ("Abre os olhos. Vazio. Luminoso. Livre.", 4.0)
            ]
        )
    }

    // MARK: - Day 23: A Tapeçaria do Momento
    private static func buildDay23() -> MeditationScript {
        return MeditationScript(
            dayNumber: 23,
            title: "A Tapeçaria do Momento",
            durationMinutes: 16,
            segments: [
                ("Senta-te como se estivesses olhando para uma tapeçaria antiga. Cada fio é um momento.", 5.0),
                ("O passado é já tecido. Fixo. Impossível de mudar. Mas também impossível de sofrer agora.", 6.0),
                ("O futuro ainda não está tecido. Pode vir de várias formas. Mas não está aqui ainda.", 6.0),
                ("Este momento? Este é o único fio que realmente tens. O único que podes tocar.", 6.0),
                ("Neste momento estão todos os teus poderes. Toda a tua capacidade. Toda a tua verdade.", 6.0),
                ("A vida não se vive no passado ou no futuro. Vive-se aqui. No fio que tecês agora.", 6.0),
                ("Observa o que está presente agora. Não o que foi. Não o que pode vir.", 6.0),
                ("Os sons que ouves. O ar que respiras. A sensação do corpo. O pensamento que passa.", 6.0),
                ("Isto é a vida real. Tudo o mais é imaginação.", 6.0),
                ("Quando ficas neste momento, sentes uma paz que não vinha. Uma presença.", 6.0),
                ("Porque não há conflito no momento. Apenas o que é. E tu aceitando o que é.", 6.0),
                ("A tapeçaria do tempo. Tecida por inúmeras momentos de presença. De aceitação.", 6.0),
                ("Cada vez que regressas ao agora, teces um fio de ouro na tapeçaria da tua vida.", 6.0),
                ("Uma vida tecida de momento em momento. Cada um um tesouro. Cada um sagrado.", 6.0),
                ("Grande silêncio. Este momento que contém tudo. Que é tudo.", 35.0),
                ("Lentamente, começa a mover-te. Mas no corpo. Neste agora.", 5.0),
                ("Abre os olhos. Vive o momento. Cada momento. Sempre.", 4.0)
            ]
        )
    }

    // MARK: - Day 24: Dissolução dos Limites
    private static func buildDay24() -> MeditationScript {
        return MeditationScript(
            dayNumber: 24,
            title: "Dissolução dos Limites",
            durationMinutes: 17,
            segments: [
                ("Senta-te e observa os limites que estabeleceste. Entre ti e os outros. Entre o dentro e fora.", 5.0),
                ("O corpo parece ser o limite. A pele é a fronteira. Mas é isto real?", 6.0),
                ("A ciência diz-nos que a pele está constantemente a trocar células com o ambiente.", 6.0),
                ("Tu não és um recipiente fechado. És uma abertura. Um processo. Um fluxo.", 6.0),
                ("O que rejeitas e chamaste \"não-eu\" está sempre contigo. Está dentro de ti.", 6.0),
                ("O que amas e chamaste \"outro\" está também dentro de ti. Na tua mente. No teu coração.", 6.0),
                ("Os limites que desenhaste são úteis para navegar a vida. Mas não são verdadeiros.", 6.0),
                ("Verdadeiramente, és ilimitado. Sem fronteiras. Unido com tudo.", 6.0),
                ("Agora, imagina estes limites a dissolver-se. Como sal na água. Como gelo ao sol.", 6.0),
                ("Sente a mente a expandir-se além do corpo. Além da casa. Além da cidade.", 6.0),
                ("Sente o coração a abrir-se para incluir toda a vida. Sem separação.", 6.0),
                ("Sente a consciência a abarcar universos. Galáxias. Dimensões que não podes nomear.", 6.0),
                ("Não há \"dentro\" e \"fora\". Não há \"eu\" e \"outro\". Apenas isto. Uma substância. Uma vida.", 6.0),
                ("Esta é a verdade do eu. Enquanto forma, pareces limitado. Mas a forma é apenas um traje.", 6.0),
                ("O que realmente és não tem limites. Podes habitar qualquer forma. Qual quer corpo. Qualquer vida.", 6.0),
                ("Grande silêncio. A dissolução dos limites. A unidade que sempre foi. Que sempre será.", 35.0),
                ("Lentamente, a forma volta. Mas sabes agora o que realmente és.", 5.0),
                ("Abre os olhos. Ilimitado. Uno. Livre.", 4.0)
            ]
        )
    }

    // MARK: - Day 25: Presença Total
    private static func buildDay25() -> MeditationScript {
        return MeditationScript(
            dayNumber: 25,
            title: "Presença Total",
            durationMinutes: 17,
            segments: [
                ("Senta-te como se fosse a última meditação da tua vida. Com total devoção.", 5.0),
                ("A presença total é estar aqui sem reservas. Sem parte de ti guardada para mais tarde.", 6.0),
                ("Muitos vivem como se a vida verdadeira começasse amanhã. Ou a semana que vem.", 6.0),
                ("Mas há apenas isto. Este momento. E a pergunta é: estás aqui?", 6.0),
                ("Estar completamente presente significa trazer toda a tua atenção. Toda a tua energia.", 6.0),
                ("Significa que o corpo está aqui. A mente está aqui. O coração está aqui.", 6.0),
                ("Não há fragmentação. Não há divisão. Apenas totalidade.", 6.0),
                ("Quando estás totalmente presente, sentes a força enorme. A vida que flui através de ti.", 6.0),
                ("Deixa de tentar controlar e apenas permite que a vida viva através de ti.", 6.0),
                ("Isto é paradoxal. Quando desistes do controle, tens o máximo de poder.", 6.0),
                ("Porque o teu poder verdadeiro não vem de tensão. Vem de alinhamento. De estar aqui.", 6.0),
                ("Agora, convida-te a estar completamente presente. Tudo de ti. Nada guardado.", 6.0),
                ("Sente como é diferente. Como é intenso. Como é vivo.", 6.0),
                ("Isto é o que foste procurando em drogas, em distrações, em buscas infinitas.", 6.0),
                ("Isto. Aqui. Agora. A verdade viva do estar presente.", 6.0),
                ("Grande silêncio. A totalidade. A completa presença. O repouso na vida.", 35.0),
                ("Lentamente, volta. Mas permanece completamente presente.", 5.0),
                ("Abre os olhos. Presente. Total. Vivo.", 4.0)
            ]
        )
    }

    // MARK: - Day 26: O Observador Puro
    private static func buildDay26() -> MeditationScript {
        return MeditationScript(
            dayNumber: 26,
            title: "O Observador Puro",
            durationMinutes: 18,
            segments: [
                ("Fecha os olhos e recua. Recua para trás de tudo o que observas.", 5.0),
                ("Não és o corpo que observas. Não és a mente que observas. Não és as emoções.", 6.0),
                ("Tens um corpo. Mas não és o corpo.", 6.0),
                ("Tens pensamentos. Mas não és os pensamentos.", 6.0),
                ("Tens sentimentos. Mas não és os sentimentos.", 6.0),
                ("Então, quem é que está aqui? A observar tudo isto?", 6.0),
                ("Este observador é puro. Não afetado pelo que observa. Como o céu que vê as nuvens.", 6.0),
                ("O céu nunca é poluído pelas nuvens negras. O céu permanece sempre céu.", 6.0),
                ("Tu és como o céu. Puro observador. A consciência que permanece intocada.", 6.0),
                ("Quando descobre isto, a vida muda. Já não podes ser ferido verdadeiramente.", 6.0),
                ("Porque o que vês como \"ti\" não é realmente tu. É apenas uma aparição.", 6.0),
                ("Tu és o espaço onde a aparição ocorre. Tu és a consciência donde vem toda a experiência.", 6.0),
                ("Não há nada para defender. Não há nada para proteger. Tu já és ileso.", 6.0),
                ("Agora, sê este observador puro. Simplesmente observa. Sem comentário. Sem reação.", 6.0),
                ("Deixa que a vida flua. Deixa que o corpo faça o seu trabalho. Deixa que a mente pense.", 6.0),
                ("Tu permaneces. O observador puro. O testemunho silencioso de tudo.", 6.0),
                ("Grande silêncio. A pureza da observação. A liberdade do observador que não participa.", 35.0),
                ("Traz isto contigo. Tu és o observador. Sempre.", 5.0),
                ("Abre os olhos. Observa. Sem ser. Sem fazer. Apenas observa.", 4.0)
            ]
        )
    }

    // MARK: - Day 27: Metta — Amor sem Condições
    private static func buildDay27() -> MeditationScript {
        return MeditationScript(
            dayNumber: 27,
            title: "Metta — Amor sem Condições",
            durationMinutes: 18,
            segments: [
                ("Senta-te no coração. Hoje cultivas o amor incondicionado. O metta. A bondade infinita.", 5.0),
                ("Este não é um amor que espera algo em troca. Não é um amor que julga ou condiciona.", 6.0),
                ("É o amor que é o coração do universo. O que sustenta toda a vida.", 6.0),
                ("Traz à mente o ser mais fácil de amar. Aquele para quem o teu coração abre naturalmente.", 6.0),
                ("Observa o amor que flui. Vê-o como uma água quente, curativa.", 6.0),
                ("Agora, estende este mesmo amor a ti próprio. Porque tu também mereçes.", 6.0),
                ("Deixa que o amor te banhe. Cura-te das feridas. Restaura-te.", 6.0),
                ("Agora, amplia. Traz todos aqueles que amas. Família. Amigos. Mestres.", 6.0),
                ("Envolvê-los em amor. Que estejam seguros. Que sejam felizes. Que sejam livres.", 6.0),
                ("Agora, traz aqueles que não conheces. Os que sofrem. Os que estão sozinhos.", 6.0),
                ("Oferece-lhes o mesmo amor. Sem discriminação. Sem julgamento.", 6.0),
                ("Agora, traz aqueles que te feriram. Que te traíram. Que te magoaram.", 6.0),
                ("Isto é difícil. Mas o rancor é veneno. E o amor é a cura.", 6.0),
                ("Oferece-lhes também metta. Porque sofrem também. Porque são prisioneiros da sua própria ignorância.", 6.0),
                ("Finalmente, expande o amor para toda a vida. Todas as criaturas. Toda a existência.", 6.0),
                ("Uma onda de amor que toca tudo. Que cura tudo. Que transforma tudo.", 6.0),
                ("Grande silêncio. O coração que transborda de amor sem condições.", 35.0),
                ("Traz este amor contigo. Para toda a vida. Para todas as seres.", 5.0),
                ("Abre os olhos. Ama. Completamente. Sempre.", 4.0)
            ]
        )
    }

    // MARK: - Day 28: Renovação Profunda
    private static func buildDay28() -> MeditationScript {
        return MeditationScript(
            dayNumber: 28,
            title: "Renovação Profunda",
            durationMinutes: 19,
            segments: [
                ("Senta-te como se estivesses no coração da terra. Aqui, tudo renova-se. Tudo é restaurado.", 5.0),
                ("Observa a vida inteira. O ciclo de morte e renovação que nunca cessa.", 6.0),
                ("A folha cai. A árvore parece morrer. Mas na primavera, vem a nova vida.", 6.0),
                ("Tu és também assim. Partes de ti morrem constantemente. Partes nascem.", 6.0),
                ("Células morrem. Neurônios morrem. Crenças antigas morrem. E novas emergem.", 6.0),
                ("Isto é renovação. Não é algo que te acontece uma vez. Está sempre a ocorrer.", 6.0),
                ("Mas podes intensificá-la. Podes trazer mais presença à renovação.", 6.0),
                ("Imagina que descestes a uma câmara subterrânea. Quente. Pulsante. Viva de energia.", 6.0),
                ("Aqui estão as águas primordiais. Aqui está a matéria de que tudo é feito.", 6.0),
                ("Agora, lava-te. Deixa que a água quente flua sobre ti. Renova-te completamente.", 6.0),
                ("Deixa que toda a fadiga saia. Toda a velha identidade. Toda a resistência.", 6.0),
                ("Renova-te. Como um fénix que sai das chamas. Novo. Inteiro. Limpo.", 6.0),
                ("A renovação não é rejeitar o que foi. É transformá-lo. Integrá-lo. Evoluir.", 6.0),
                ("Tu já não és quem eras. E ainda não és quem te tornarás. Estás no meio.", 6.0),
                ("Este meio é sagrado. É aqui que toda a transformação ocorre.", 6.0),
                ("Grande silêncio. A terra que renova. A vida que se renova através de ti.", 38.0),
                ("Lentamente, volta para cima. Renovado. Transformado. Reborn.", 5.0),
                ("Abre os olhos. Novo. Sempre novo. Eternamente novo.", 4.0)
            ]
        )
    }

    // MARK: - Day 29: O Grande Silêncio
    private static func buildDay29() -> MeditationScript {
        return MeditationScript(
            dayNumber: 29,
            title: "O Grande Silêncio",
            durationMinutes: 19,
            segments: [
                ("Senta-te em silêncio absoluto. Ou o mais silencioso que conseguires.", 5.0),
                ("Observa o silêncio. Não o silêncio da ausência de som. O silêncio da presença.", 6.0),
                ("Um silêncio que é vivo. Que respira. Que contém toda a vida potencial.", 6.0),
                ("No princípio, havia silêncio. E do silêncio veio toda a criação.", 6.0),
                ("Toda a palavra, toda a música, toda a conversa vem do silêncio.", 6.0),
                ("E para o silêncio regressará quando o som terminar.", 6.0),
                ("O silêncio é o lar de tudo. A matriz de tudo. A verdade de tudo.", 6.0),
                ("Quando deixas a mente de falar, entras no silêncio. E o silêncio fala.", 6.0),
                ("Fala em verdades que a mente nunca poderia dizer.", 6.0),
                ("Fala em comunhão. Em união. Em totalidade.", 6.0),
                ("Agora, deixa todo o discurso mental. Deixa todas as histórias. Deixa toda a tradução.", 6.0),
                ("Apenas permanece. No silêncio. Como se fosse a única coisa que realmente existe.", 6.0),
                ("Grande silêncio. O silêncio que é a base de tudo. A verdade além das palavras.", 45.0),
                ("Quando a campainha soa, quando o tempo termina, sabes que ainda estás no silêncio.", 5.0),
                ("Porque agora o silêncio caminha contigo. Para onde quer que vás.", 5.0),
                ("Abre os olhos. Silencioso. Eternamente silencioso.", 4.0)
            ]
        )
    }

    // MARK: - Day 30: Celebração do Ser
    private static func buildDay30() -> MeditationScript {
        return MeditationScript(
            dayNumber: 30,
            title: "Celebração do Ser",
            durationMinutes: 20,
            segments: [
                ("Senta-te como se estivesse na celebração do universo. Porque estás. Este é o seu festa.", 5.0),
                ("Trinta dias. Trinta meditações. Trinta encontros com a verdade do teu ser.", 6.0),
                ("E agora reconhecem: não vai terminar. A meditação não termina aqui.", 6.0),
                ("Cada momento é meditação. Cada respiração é celebração. Cada encontro é sagrado.", 6.0),
                ("Tu já foste brindado pelo silêncio. Já dançaste com a eternidade. Já morreu e renasceu.", 6.0),
                ("Tu já tocaste o infinito. Já habitaste o vazio. Já amaste sem condição.", 6.0),
                ("O que ainda há para fazer? Nada. Tudo foi já feito.", 6.0),
                ("Agora é o tempo da celebração. De gratidão. De reconhecimento.", 6.0),
                ("Celebra que tu és. Aqui. Agora. Nesta forma, com este nome, com esta jornada.", 6.0),
                ("Celebra o corpo que te permitiu conhecer o mundo. As mãos que criaram. Os olhos que viram.", 6.0),
                ("Celebra o coração que amou. Que sofreu. Que aprendeu. Que cresceu.", 6.0),
                ("Celebra a mente que questionou. Que se maravilhou. Que vislumbrou a verdade.", 6.0),
                ("Celebra todos aqueles que te tocaram. Que te ensinaram. Que te transformaram.", 6.0),
                ("Celebra até mesmo as dificuldades. As falhas. Os erros. Porque te tornaram quem és.", 6.0),
                ("Celebra o universo que te contém. As estrelas que brilham acima. A terra que suporta.", 6.0),
                ("Tu és um milagre. Uma expressão singular do universo a conhecer-se a si próprio.", 6.0),
                ("Há alegria nisto. Há uma graça nisto. Há uma beleza que não pode ser dita.", 6.0),
                ("Grande silêncio. A celebração que é silenciosa. O júbilo do ser.", 40.0),
                ("Lentamente, abre os olhos. A celebração continua. Dia após dia. Vida após vida.", 5.0),
                ("Abre os olhos completamente. Celebra. Sempre celebra. O milagre do ser.", 4.0)
            ]
        )
    }
}
